version: "3.7"

services:
  fluent-bit:
    image: fluent/fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./test.log:/var/test.log
      - ./custom_parsers.conf:/fluent-bit/etc/custom_parsers.conf
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:7.6.2
    platform: linux/x86_64
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
